trigger:
- main


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: PackageAndBuild
    steps:
    - task: CmdLine@2
      inputs:
        script: 'wget https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: 'apache-maven-3.9.6-bin.zip'
        destinationFolder: '$(Build.SourcesDirectory)/maven'
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@3
      inputs:
        mavenPomFile: '$(APP_NAME)/pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Path'
        mavenDirectory: '$(Build.SourcesDirectory)/maven/apache-maven-3.9.6'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/$(APP_NAME)/target'
        Contents: '$(APP_NAME)-runner.jar'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(APP_NAME)'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to petpals-pals
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '$(APP_NAME)'
        itemPattern: '**/*.jar'
        downloadPath: '$(System.ArtifactsDirectory)'
        checkDownloadedFiles: true
    - task: CopyFiles@2
      displayName: 'Copy Files from artifact staging directory'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/$(APP_NAME)'
        Contents: '$(APP_NAME)-runner.jar'
        TargetFolder: '$(System.DefaultWorkingDirectory)'
        OverWrite: true
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(1)(f1248dd5-2384-4478-bf73-b940c14b63dc)'
        appType: 'webAppLinux'
        appName: '$(APP_NAME)'
        package: '$(System.DefaultWorkingDirectory)/$(APP_NAME)-runner.jar'
        runtimeStack: 'JAVA|17-java17'
        startUpCommand: 'java -jar /home/site/wwwroot/$(APP_NAME)-runner.jar'
        appSettings: '-WEBSITES_PORT 80'
        configurationStrings: '-PORT 80'
